name: Gridify Layout Proposal
description: Propose a custom `gridify` layout that could be useful for others, such as your organization.
title: "Gridify Layout Proposal: <Insert Layout Name Here>"
labels: ["gridify layout", "enhancement"]
assignees:
  - polkas
body:
  - type: markdown
    attributes:
      value: |
        **Challenge:** 
        Create a custom `gridify` layout that is both functional and inspiring. 
        You have full flexibility, each text element can have its own styling.
        [Please read more about custom layouts here](https://pharmaverse.github.io/gridify/articles/create_custom_layout.html).

        **Example Inspiration:** 
        A layout used in the `gridify` poster for PHUSE EU 2025.

        ```r
        library(gridify)
        library(gt)
        library(random.cdisc.data)

        example_custom_layout <- gridifyLayout(
            nrow = 3,
            ncol = 4,
            heights = grid::unit(c(1, 1, 1), c("lines", "null", "lines")),
            widths = grid::unit(c(1/4, 1/4, 1/4, 1/4), "npc"),
            margin = grid::unit(c(0.5, 0.5, 0.5, 0.5), "inches"),
            global_gpar = grid::gpar(
              fontfamily = "serif", 
              fontsize = 14, 
              col = "black", 
              fontface = "bold"
            ),
            background = grid::get.gpar()$fill,
            adjust_height = TRUE,
            object = gridifyObject(row = 2, col = 1:2),
            cells = gridifyCells(
              title = gridifyCell(row = 1, col = 1:2, x = 1, hjust = 0.5, gpar = grid::gpar(fontsize=18)),
              poem = gridifyCell(row = 2, col = 3:4, x = 0.1, hjust = 0, y = 0.5),
              footer_company = gridifyCell(row = 3, col = 1, x = 0, hjust = 0),
              footer_powered = gridifyCell(row = 3, col = 4, x = 0, hjust = 0)
            )
          )

        gg <- gt::gt(
          cadsl |>
            dplyr::group_by(ARM, REGION1)|>
            dplyr::summarise(
              `MEAN AGE` = round(mean(AGE), 2), 
              `MEAN BMRKR1` = round(mean(BMRKR1), 2)
            )
        ) |>
          gt::tab_options(
            table.width = gt::pct(80),  # Increased from 10% to 80%
            data_row.padding = gt::px(10),
            table_body.hlines.color = "black",table.font.color = "black", 
            table.font.weight = "bold",row_group.font.weight = "bold",
            table.font.size = 14,
            # Add complementary blue background styling
            table.background.color = "white",  # Slightly lighter blue than layout
            heading.background.color = "white",
            column_labels.background.color = "white",
            table_body.border.top.color = "white",
            table_body.border.bottom.color = "white"
          ) |>
          # Use tab_style() to set font colors to white for visibility on blue background
          gt::tab_style(
            style = gt::cell_text(color = "black", weight = "bold"),
            locations = gt::cells_column_labels()
          ) |>
          gt::tab_style(
            style = gt::cell_text(color = "#00158F", weight = "bold"),
            locations = gt::cells_column_labels()
          ) |>
          gt::tab_style(
            style = gt::cell_text(color = "#00158F", weight = "bold"),
            locations = gt::cells_row_groups()
          )

        gridify_object <- gridify(
          object = gg,
          layout = example_custom_layout
        )

        gridify_object_fill <- gridify_object |>
          set_cell("title", "Gridify's Creative Call") |> #, gpar = grid::gpar(col = "#B8E2F4")) |>
          set_cell("poem", "'When standard layouts feel too plain,
        And your reports need that custom flair,
        Gridify invites you to design and share,
        A layout that shows how much you care.
        With flexible styling for every text,
        Create something bold, something complex,
        Scan the QR code, propose your best,
        Join the community, pass the creative test.
        From corporate branding to research needs,
        Your custom layout plants the seeds,
        For others seeking that perfect frame,
        To showcase data and stake their claim.'\nAnonymous", gpar = grid::gpar(fontface = "bold.italic")) |>
          set_cell("footer_company", "UCB team") |> #, gpar = grid::gpar(col = "#B8E2F4")) |>
          set_cell("footer_powered", "Powered by gridify", gpar = grid::gpar(fontsize = 18, fontface = "bold")) |>
          print()
        ```
  - type: textarea
    id: layout-purpose
    attributes:
      label: Purpose of the Layout
      description: What is the goal of your layout? Who is it for? What kind of content does it best support?
      placeholder: "Example: A layout for internal dashboards that highlights KPIs and team updates in a visually engaging way."
    validations:
      required: true

  - type: textarea
    id: layout-details
    attributes:
      label: Layout Structure & Styling
      description: Describe the structure of your layout (rows, columns, cell assignments) and any specific styling choices (fonts, colors, spacing).
      placeholder: "Example: 3 rows, 4 columns, serif font, bold headers, blue accents. Title spans top row, grouped data in middle, footer with company branding."
    validations:
      required: true

  - type: textarea
    id: code-snippet
    attributes:
      label: Code Snippet
      description: Share a snippet of your `gridifyLayout()` and `gridifyCells()` code if available.
      placeholder: "Paste your R code here..."
    validations:
      required: false
