name: Gridify Layout Proposal
description: Propose a custom `gridify` layout that could be useful for others, such as your organization.
title: "Gridify Layout Proposal: <Insert Layout Name Here>"
labels: ["gridify layout", "enhancement"]
assignees:
  - polkas
body:
  - type: markdown
    attributes:
      value: |
        Create a custom `gridify` layout that is both functional and inspiring. 
        You have full flexibility, each text element can have its own styling.
        [Please read more about custom layouts here](https://pharmaverse.github.io/gridify/articles/create_custom_layout.html).
  - type: textarea
    id: layout-purpose
    attributes:
      label: Purpose of the Layout
      description: What is the goal of your layout? Who is it for? What kind of content does it best support?
      placeholder: "Example: A layout for internal dashboards that highlights KPIs and team updates in a visually engaging way."
    validations:
      required: true

  - type: textarea
    id: layout-details
    attributes:
      label: Layout Structure & Styling
      description: Describe the structure of your layout (rows, columns, cell assignments) and any specific styling choices (fonts, colors, spacing).
      placeholder: "Example: 3 rows, 4 columns, serif font, bold headers, blue accents. Title spans top row, grouped data in middle, footer with company branding."
    validations:
      required: true

  - type: textarea
    id: code-snippet
    attributes:
      label: Code Snippet
      description: Share a snippet of your `gridifyLayout()` and `gridifyCells()` code if available.
      placeholder: |
        **Example Inspiration:** 
        
        A layout used in the `gridify` poster for PHUSE EU 2025.

        ```r
        library(gridify)
        example_custom_layout <- gridifyLayout(
            nrow = 3,
            ncol = 4,
            heights = grid::unit(c(1, 1, 1), c("lines", "null", "lines")),
            widths = grid::unit(c(1/4, 1/4, 1/4, 1/4), "npc"),
            margin = grid::unit(c(0.5, 0.5, 0.5, 0.5), "inches"),
            global_gpar = grid::gpar(
              fontfamily = "serif", 
              fontsize = 14, 
              col = "black", 
              fontface = "bold"
            ),
            background = grid::get.gpar()$fill,
            adjust_height = TRUE,
            object = gridifyObject(row = 2, col = 1:2),
            cells = gridifyCells(
              title = gridifyCell(row = 1, col = 1:2, x = 1, hjust = 0.5, gpar = grid::gpar(fontsize=18)),
              poem = gridifyCell(row = 2, col = 3:4, x = 0.1, hjust = 0, y = 0.5),
              footer_company = gridifyCell(row = 3, col = 1, x = 0, hjust = 0),
              footer_powered = gridifyCell(row = 3, col = 4, x = 0, hjust = 0)
            )
          )
        ```
    validations:
      required: false

